### ISSUE TITLE
Stopped works with the last release (1.2.7) with Angular 5/6

### ISSUE THREAD

**Issue by oksanamuz** [abacritt/angularx-social-login#181]
ERROR in node_modules/angularx-social-login/src/providers/facebook-login-provider.d.ts(10,35): error TS1039: Initializers are not allowed in ambient contexts.

**Comment by Mariam13** [comment]
+ also with angular 6

**Comment by tpps88206** [comment]
Same issue with 

`angular  6.1.10`
`angular cli 6.2.9`
`node 10.15.0`

I built successfully at 5/9. And I was failed now.

**Comment by jaibatrik** [comment]
Can you please tell us when the error occurs?

**Comment by tpps88206** [comment]
@jaibatrik `ng serve` and `ng build --configuration=production --prod --build-optimizer`

```bash
$ ng build --configuration=production --prod --build-optimizer
Your global Angular CLI version (7.2.1) is greater than your local
version (6.2.9). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

Date: 2019-05-18T14:48:55.003Z
Hash: edabc49e8d0c8487571b
Time: 12667ms
chunk {scripts} scripts.208c72b922d4e69cdb09.js (scripts) 8.62 MB  [rendered]
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.05 kB [entry] [rendered]
chunk {1} styles.8ed3315dae4b28f4861e.css (styles) 265 kB [initial] [rendered]
chunk {2} polyfills.e7f5364b276024e19b0b.js (polyfills) 130 bytes [initial] [rendered]
chunk {3} main.0594610c91de797f492a.js (main) 128 bytes [initial] [rendered]

ERROR in node_modules/angularx-social-login/src/providers/facebook-login-provider.d.ts(10,35): error TS1039: Initializers are not allowed in ambient contexts.
```

```bash
$ ng serve
Your global Angular CLI version (7.2.1) is greater than your local
version (6.2.9). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wds｣: Project is running at http://localhost:4200/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to //index.html

Date: 2019-05-20T02:06:09.153Z
Hash: a11b3a497826f398a24a
Time: 10347ms
chunk {main} main.js, main.js.map (main) 344 kB [entry] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 344 kB [entry] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 8.26 MB  [rendered]
chunk {styles} styles.js, styles.js.map (styles) 754 kB [entry] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 10.2 kB [initial] [rendered]

ERROR in node_modules/angularx-social-login/src/providers/facebook-login-provider.d.ts(10,35): error TS1039: Initializers are not allowed in ambient contexts.

ℹ ｢wdm｣: Failed to compile.
```

**Comment by jaibatrik** [comment]
Can you guys please post TypeScript version you are using?

**Comment by oksanamuz** [comment]
> Can you guys please post TypeScript version you are using?

typescript 2.7.0 - it's the latest possible for angular 5. But I supposed that guys with Angular 6 uses fresher version.

**Comment by tpps88206** [comment]
> Can you guys please post TypeScript version you are using?

typescript 2.9.2

```bash
Angular CLI: 6.2.9
Node: 10.15.0
OS: darwin x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cdk                      6.4.7
@angular/cli                      6.2.9
@angular/material                 6.4.7
@angular/pwa                      0.7.5
@ngtools/webpack                  6.0.8
@schematics/angular               0.7.5
@schematics/update                0.8.9
rxjs                              6.5.2
typescript                        2.9.2
webpack                           4.8.3
```

**Comment by jaibatrik** [comment]
According to multiple StackOverflow posts, code compiled with TS 3+ is not compatible with TS 2.X. I think, for now, people with Angular 5 / 6 have to use an older version of the library, such as 1.2.6.

**Comment by Camilotk** [comment]
I'm using Angular 6 and had the same issue. I've tryed a lot of different solutions from github, stack's and google for don't have to modify my packages.json, but none worked. I'm using 1.2.6 now, any chance of this could be compiled with TS 2.9 in future versions?

**Comment by jaibatrik** [comment]
@Camilotk You can clone the project, change the TS version in the package.json and build the library yourself.

**Comment by Camilotk** [comment]
Ok. I didn't reallized that I could just compile by myself, sorry about
that.

Em qua, 22 de mai de 2019 às 13:03, Jaibatrik Dutta <
notifications@github.com> escreveu:

**Comment by Camilotk** [comment]
@jaibatrik Ok, I'll do it. Just didn't reallized that was just compile it by myself. Thanks.

**Comment by kalashnikovisme** [comment]
Downgraded library to version 1.2.6
everything is ok now

**Comment by oksanamuz** [comment]
Obviously, that we need to hardcode version to 1.2.6, I needed 10 min to determinate this, but I expected to see at least warnings that my version of the TS is incompatible to the current version during `npm i`, and to not see errors during build project... Not sure how now, but when I created this issue any errors/warnings weren't presented during node modules installation.

**Comment by oksanamuz** [comment]
Any chance that you (developers of this module :) ) can add any check for this, maybe in the dependencies? For example like in Angular Material, if you try to install version 8 with angular 7 it notifies users, the angular 8 is required.

**Comment by jaibatrik** [comment]
I think the best solution to this would be to maintain a compatibility table for the module. I'll update the README during the weekend.

**Comment by zawars** [comment]
```
ERROR in Value at position 0 in the NgModule.importss of SocialLoginModule is not a reference: [object Object]
```

**Comment by jaibatrik** [comment]
I am closing this. As the library is upgraded to use the latest Angular version, it is not possible to support all the Angular versions with latest version of the library. People using Angular 5 / 6 can use version 1.2.6 of the library.
