### ISSUE TITLE
Error: Login providers not ready yet

### ISSUE THREAD

**Issue by RonRofe** [abacritt/angularx-social-login#280]
![צילום מסך 2020-06-16 ב-11 44 41](https://user-images.githubusercontent.com/30625668/84752727-cd3e0280-afc6-11ea-99cf-3395d2065af0.png)

I get the following error when trying to perform 
```typescript
constructor(private socialAuthService: SocialAuthService,) {}

ngOnInit() {
   this.socialAuthService.signIn(FacebookLoginProvider.PROVIDER_ID);
}
```

app.module.ts
```typescript
import { SocialLoginModule, SocialAuthServiceConfig, FacebookLoginProvider } from 'angularx-social-login';
...
    {
      provide: 'SocialAuthServiceConfig',
      useValue: {
        autoLogin: false,
        providers: [
          {
            id: FacebookLoginProvider.PROVIDER_ID,
            provider: new FacebookLoginProvider('...'),
          },
        ],
      } as SocialAuthServiceConfig,
    },
...
```

Angular version: 9
"angularx-social-login": "^3.0.0",

**Comment by videmort** [comment]
Same here

**Comment by sufiiiyan** [comment]
Facing same issue
![image](https://user-images.githubusercontent.com/12623084/84857249-3a649d00-b086-11ea-8dea-086e46beaa43.png)

**Comment by jaibatrik** [comment]
Looking into this.

**Comment by jaibatrik** [comment]
I tried to reproduce this, and could not. It worked for me. Could you guys provide me with a small replication repo / codebase / sample?

Also, I can see from @sufiiiyan's screenshot that the Facebook and Google JS did not get loaded, which is probably the reason for this issue. Can you please check why this is the case?

**Comment by jaibatrik** [comment]
Are all of you trying to call `signIn` in `ngOnInit`? To think of it, that might cause problems.

Want to ask out of curiosity, what is the use case for calling `signIn` in the component load itself?

**Comment by RonRofe** [comment]
> Are all of you trying to call `signIn` in `ngOnInit`? To think of it, that might cause problems.
> 
> Want to ask out of curiosity, what is the use case for calling `signIn` in the component load itself?

My particular use case was only to test it. But I think it should be fixed since it should be working on all cases.
But yes, indeed the issue raises only when using it inside ngOnInit().

Lets take for example a case when a user clicks a button "login with facebook" which opens a new dialog components with the content: 'Login with facebook, please wait..." - Now you want to start the process in ngOnInit().

**Comment by RonRofe** [comment]
> Are all of you trying to call `signIn` in `ngOnInit`? To think of it, that might cause problems.
> 
> Want to ask out of curiosity, what is the use case for calling `signIn` in the component load itself?

Do you also know how to verify the auth token on the backend? Which ENDPOINT should be used for this?

**Comment by JussV** [comment]
Facing the same issue with Angular 9 and version 3.0.0 of angularx-social-login.
Google and fb scripts are loaded correctly as you can see from the screenshot.
<img width="1790" alt="Screen Shot 2020-06-17 at 12 26 18" src="https://user-images.githubusercontent.com/6590253/84887311-d9dd5c00-b095-11ea-90fe-1fedb9c8845c.png">
<img width="804" alt="Screen Shot 2020-06-17 at 12 26 30" src="https://user-images.githubusercontent.com/6590253/84887320-dc3fb600-b095-11ea-97cc-e72aeaa0ef0c.png">

**Comment by jaibatrik** [comment]
@JussV Thanks for the helpful analysis. I guess `SocialAithService.initialize()` should use `Promise.allSettled` or `Promise.finally` instead of `Promise.all`. 

The `GoogleLoginProvider` is indeed resolving in the following block - 
```javascript
this.auth2
  .then(() => {
    resolve();
  })
```

**Comment by jaibatrik** [comment]
At this point, I am not making any change for the scenario where `signIn` is being called on `onInit`. I'll probably change the message to be a bit more informative. I'll also change the `initialize` functions in `SocialAuthService` and providers to have proper error propagation.

However, if others are not calling `signIn` on `onInit`, I'd like to look at those scenarios. Can any of you please provide me with a sample?

**Comment by JussV** [comment]
> @JussV Thanks for the helpful analysis. I guess `SocialAithService.initialize()` should use `Promise.allSettled` or `Promise.finally` instead of `Promise.all`.
> 
> The `GoogleLoginProvider` is indeed resolving in the following block -
> 
> ```js
> this.auth2
>   .then(() => {
>     resolve();
>   })
> ```
> 
> Do you see any other error on the console by any chance?

@jaibatrik for the case of Google provider it does not go in resolve() or reject() blocks. While I was debbuging I noticed that strange behavior that after invoking ```
gapi.auth2.init(Object.assign(Object.assign({}, this.initOptions), { client_id: this.clientId }));
``` this.auth2 has result in it, but does not resolve neither rejects and no other errors in console are thrown despite _Login providers not ready._

**Comment by anirudh54** [comment]
facing the same issue guys and i am not using signin on init.

**Comment by jaibatrik** [comment]
Can any of you provide a simple repo where I can see the issue in action? It's working for me, it's working in the demo app in this repository.

**Comment by jaibatrik** [comment]
@JussV According to the documentation at https://developers.google.com/identity/sign-in/web/reference, the `resolve` should get called when the `init(params)` is done initializing. May be there's some problem in this initialization?

**Comment by jaibatrik** [comment]
Also, since the demo app in this repo is working, could you guys check if there's any difference in the implementation that might be causing the problem?

**Comment by dbmuller** [comment]
This demo page has the same error when attempting sign in on all platforms
https://abacritt.github.io/angularx-social-login/

![image](https://user-images.githubusercontent.com/18412052/85263424-7ea2d380-b4b2-11ea-91cc-fd3df6e8d447.png)

**Comment by jaibatrik** [comment]
This is strange. I can use the demo site and login with FB without any problem. Is the problem specific to environment then? Works in Chrome and Firefox for me.

![image](https://user-images.githubusercontent.com/1858403/85279572-472d2a80-b4a4-11ea-9c54-3898af2ed967.png)

**Comment by jaibatrik** [comment]
@dbmuller Could you please post screenshot of the whole console with all logging levels on?

**Comment by dbmuller** [comment]
@jaibatrik yes sure can.  So there's no cache to worry about, I'm new to this package and it was broken first load.  I ctrl+F5 anyway just in case.
This is in Chrome 83.0.4103.106 (Official Build) (64-bit)

I opened it in Edge and IE 11 and it worked.

Attached is the Console Log plus screen shot.  
[abacritt.github.io-1592823823947.log](https://github.com/abacritt/angularx-social-login/files/4812805/abacritt.github.io-1592823823947.log)

![image](https://user-images.githubusercontent.com/18412052/85280771-25479e00-b4cc-11ea-8443-f5ab1d648b6f.png)

Below I tried it in Tor, and same error
![image](https://user-images.githubusercontent.com/18412052/85280924-7788bf00-b4cc-11ea-9c00-f27d544c38e5.png)

**Comment by jaibatrik** [comment]
Looks like in @dbmuller's case, the error is coming because Facebook JS SDK not getting loaded. At the top of the console, we see `net::ERR_BLOCKED_BY_CLIENT` for https://connect.facebook.net/en_US/sdk.js

So far, we have seen multiple causes for this - 
1. Calling `signIn` in component load itself - not fixing it right away, probably not that popular use-case.
1. Google's library not invoking callback after initialization - need a sample or environment to see / debug this issue.
1. Facebook library JS not getting loaded - @dbmuller could you please disable any ad-blocker you have and try and let us know?

**Comment by dbmuller** [comment]
I enabled scripts from Facebook and that fixed it.  Just to confirm, blocking Facebook breaks log in to any services.

**Comment by jaibatrik** [comment]
> I enabled scripts from Facebook and that fixed it.  Just to confirm, blocking Facebook breaks log in to any services.

Thanks! Yeah, have to fix this single point of failure.

**Comment by EdwardSin** [comment]
I was facing this issue.
Just to make sure that all of the provided providers details are able to do the login.
It might be not include the URL in provider whitelist, or the provider details is incorrect.
Any of them is failed then will lead to the "Login providers not ready yet" error.

**Comment by jaibatrik** [comment]
Need a better error reporting. I should be able to make the changes by this weekend. Thanks everyone for your help!

**Comment by veteran1** [comment]
had the same probleme, when I opened my application in uncognito tab it worked, try to do a hard refresh (alt+f5 wont work)
 

[img](https://i.stack.imgur.com/4xfwi.png "hard refresh")

**Comment by Blucbo** [comment]
same issue with google

**Comment by LeeiinadBr** [comment]
For those who are trying to `signIn` on component load, you might as well set `autoLogin: true` in `SocialAuthServiceConfig`.

In case you need another solution, though, I came up with a workaround. However, I highly discourage using it, as it modifies original code (and the implementation is very poor, as I'm new to creating Observables - probably not the best solution anyways). It essentially creates an Observable that emits the new value of `initialized`, which gets changed to true when the providers are ready (refer to socialauth.service.js).

(Refer to following structure:)
```
<parent-component>
  <child-component></child-component>
</parent-component>
```

First, you'll need to modify the original `socialauth.service.d.ts` file, exposing (in this case, changing property from _private_ to **public**)  the `initialized` property of the `SocialAuthService` class:
```
export declare class SocialAuthService {
  // ...
  public initialized;
  // ...
}
```
Afterwards, you'll inject the SocialAuthService in your parent component:
```
export class ParentComponent implements OnInit {
  // ...
  constructor(private authService: SocialAuthService) { }
  // ...
}
```
Then, create a method (or getter) that returns an `Observable<boolean>` which emits the exposed `initialized` property:
```
export class ParentComponent implements OnInit {
// ...
isInitialized(): Observable<boolean> {
    return new Observable((observer) => {
      if (this.authService.initialized) {
        observer.next(this.authService.initialized);
        observer.complete();
        observer.unsubscribe();
      } else {
        observer.next(this.authService.initialized);
      }
    });
}
// ...
```
(Again, I have not worked with creating observables before, this implementation is very simple and can/should be improved.)

Finally, use the `*ngIf` directive with `isInitialized() | async` in your parent template:
```
<parent-component>
  <child-component *ngIf="isInitialized() | async"></child-component>
</parent-component>
```

This workaround ensures that the child component will only be generated when the providers are ready.
Again, probably poor solution, but decided to share it to people that are looking for a quickfix.

Another fix would be simply to `setTimeout` on child component load and inside callback call the `signIn` method, however the initialization time may vary between different internet connections/browsers.

In any case, be sure to always handle the errors correctly. The providers may never get ready, if an error occurs, so pay attention to that. Recommend timing out the Observable as well after some time.

**Comment by jaibatrik** [comment]
@LeeiinadBr Thanks for pointing out the workaround! I'll add a method to indicate the initialization status.

**Comment by jaibatrik** [comment]
Added an `initState` observable to `SocialAuthService`. It will complete once all the providers are ready. This should help with calling `signIn` on component load.

Usage: `this.authService.initState.subscribe(() => {}, console.error, () => {console.log('all providers are ready')});`

The problem with centralized handling of providers is not yet solved though. TypeScript is still not supporting `Promise.allSettled`. Once that is there, will handle individual provider statuses properly.

**Comment by chaoka** [comment]
Just got the issue, the culprit(s) were uBlock origin AND an agressive Firefox tracking protection. Check any extension and firefox configuration that might prevent downloading third party libraries.

**Comment by csbenjamin** [comment]
@jaibatrik I was having this issue too. I am not calling `signIn` on `ngOnInit`. But sometimes, when the user clicks on google sign button as soon as the page loads, we got the error. If the user waits a little bit, the signIn method works fine. 
Now that we have`authService.initState`, when the user clicks on the button, we wait that observable to complete before call the `signIn` method.
What do you think about, inside the `signIn` method, waiting `authService.initState` to complete before proceeding?

**Comment by jaibatrik** [comment]
> @jaibatrik I was having this issue too. I am not calling `signIn` on `ngOnInit`. But sometimes, when the user clicks on google sign button as soon as the page loads, we got the error. If the user waits a little bit, the signIn method works fine.
> Now that we have`authService.initState`, when the user clicks on the button, we wait that observable to complete before call the `signIn` method.
> What do you think about, inside the `signIn` method, waiting `authService.initState` to complete before proceeding?

That might mean that `signIn()` might wait infinitely though.

**Comment by csbenjamin** [comment]
@jaibatrik So, are there cases where `initState` does not complete? What are the cases? Because I will have the same problem when waiting `initState` to complete in my component.

**Comment by jaibatrik** [comment]
In the current setup, if one of the providers take forever to load, the initState will be held up I think.

**Comment by csbenjamin** [comment]
But, if some provider take forever to load and the user clicks on the button of that provide, `signIn` will not work. It would be great if we can check if a specific provide was loaded. What do you think?

**Comment by jaibatrik** [comment]
Yeah, that might be what we'll need to do. I wanted to keep it simple, but probably doing that will be needed.

**Comment by RohitGCoder** [comment]
I am facing similar issue 
On console I am getting

`629106217-idpiframe.js:104 GET https://accounts.google.com/o/oauth2/iframerpc?action=checkOrigin&origin=http%3A%2F%2Flocalhost%3A4200&client_id=Google-OAuth-Client-Id 401
ge @ 629106217-idpiframe.js:104
he @ 629106217-idpiframe.js:104
(anonymous) @ 629106217-idpiframe.js:130
(anonymous) @ 629106217-idpiframe.js:112
m.getItem @ 629106217-idpiframe.js:90
S.B @ 629106217-idpiframe.js:112
Ie @ 629106217-idpiframe.js:125
We @ 629106217-idpiframe.js:129
m.Pc @ 629106217-idpiframe.js:132
(anonymous) @ 629106217-idpiframe.js:142
ye.Tc @ 629106217-idpiframe.js:120
b @ 629106217-idpiframe.js:131
zone-evergreen.js:364 {error: "idpiframe_initialization_failed", details: "Not a valid origin for the client: http://localhos…itelist this origin for your project's client ID."}
invoke @ zone-evergreen.js:364
onInvoke @ core.js:41654
invoke @ zone-evergreen.js:363
run @ zone-evergreen.js:123
(anonymous) @ zone-evergreen.js:857
invokeTask @ zone-evergreen.js:399
onInvokeTask @ core.js:41632
invokeTask @ zone-evergreen.js:398
runTask @ zone-evergreen.js:167
drainMicroTaskQueue @ zone-evergreen.js:569
invokeTask @ zone-evergreen.js:484
invokeTask @ zone-evergreen.js:1621
globalZoneAwareCallback @ zone-evergreen.js:1658
core.js:6228 ERROR Error: Uncaught (in promise): Login providers not ready yet. Are there errors on your console?
    at resolvePromise (zone-evergreen.js:798)
    at zone-evergreen.js:705
    at angularx-social-login.js:67
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at SocialAuthService.signIn (angularx-social-login.js:65)
    at LoginComponent.signInWithFB (login.component.ts:36)
    at LoginComponent_Template_button_click_13_listener (login.component.html:20)
    at executeListenerWithErrorHandling (core.js:21806)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:21848)
    at HTMLButtonElement.<anonymous> (platform-browser.js:976)
defaultErrorLogger @ core.js:6228
handleError @ core.js:6281
next @ core.js:42614
schedulerFn @ core.js:37119
__tryOrUnsub @ Subscriber.js:183
next @ Subscriber.js:122
_next @ Subscriber.js:72
next @ Subscriber.js:49
next @ Subject.js:39
emit @ core.js:37079
(anonymous) @ core.js:41694
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:123
runOutsideAngular @ core.js:41488
onHandleError @ core.js:41691
handleError @ zone-evergreen.js:368
runGuarded @ zone-evergreen.js:136
api.microtaskDrainDone @ zone-evergreen.js:670
drainMicroTaskQueue @ zone-evergreen.js:576
invokeTask @ zone-evergreen.js:484
invokeTask @ zone-evergreen.js:1621
globalZoneAwareCallback @ zone-evergreen.js:1647`

And in component file:-

`export class LoginComponent implements OnInit {

  user: SocialUser;
  loggedIn: boolean;
  constructor(private authService: SocialAuthService) { }
 
  ngOnInit() {
    //Get User Data
     this.authService.authState.subscribe((user) => {
        console.log('Logged in now: ', user);
      this.user = user;
      this.loggedIn = (user != null);
    });
  }

   //Login
  signInWithG(): void {
    this.authService.signIn(GoogleLoginProvider.PROVIDER_ID);
  
  } 
}`

**Comment by jennyliulfm** [comment]
I had the same issue before, but just now I integrated the demo code to my project, it works now. The only difference between demo code and my code is : autoLogin. Setting autoLogin as true fixes my problem.

**Comment by webcat12345** [comment]
Yes, waiting for few seconds resolves the problem. Feeling is not good but thanks for a workaround.

**Comment by kapilSoni101** [comment]
anybody have fix above issue

**Comment by i-aleksandrov** [comment]
If you are using adblocker or your browser is configured on 'strict' and blocks cookies and trackers, social login will not work. Try on a browser with less strict tracking restrictions policy and you may solve your problem.

**Comment by jaibatrik** [comment]
Not getting much time these days. I'd really appreciate if somebody makes the changes to `SocialAuthService` to make it work only with the ready providers.

**Comment by VietHoc** [comment]
Make sure your have **client_id** of google or facebook.

**Comment by sumit24745** [comment]
I have done "empty cache and hard reload" and now it is working fine. 
https://prnt.sc/uaa040

**Comment by fabriziogelsi** [comment]
Hello, I am having the same issue as @csbenjamin and @webcat12345 , if you wait just a few seconds... the provider is ready. But if you try to call it (click in the sign-in button, I'm not calling on ngInit), but calling it by click on the button as soon as the page load, the alert with "Login providers not ready yet" appears... Idk what workaround try... And on the otherhand, what about autoLogin? What is the feature? Because I use as "true" but, after 1hour, when the token expires, I have to login again, on the googlePopup...

**Comment by hardwinsoftware** [comment]
This problem occurs on google chrome running on incognito window.@jaibatrik could you please check in incognito mode?

**Comment by fabriziogelsi** [comment]
I have this problem in Chrome (not incognito window)

**Comment by hardwinsoftware** [comment]
> I have this problem in Chrome (not incognito window)

As per my analysis the variable `this.initialized` is not setting to true on incognito mode and the promise block which initializes the providers is not executing at all on incognito mode.

**Comment by Mannymonster** [comment]
Hi.

The Google login was throwing the error when my project wasn't using https. I enabled --ssl true on my localhost, it now allows me to open the Google log in. 
Seems to be something to do with https. 


Hope this helps.

**Comment by brucremo** [comment]
Hello everyone,

In addition to the issues mentioned, Firefox has an issue loading the .js from Facebook, due to Firefox's own settings. It's quite an old issue actually, you can take a look at:

https://support.mozilla.org/en-US/questions/1130053

Would it be possible to set a dynamic path for the third party scripts for loading? Because on production it's not possible to just disable that config while using Firefox, since it's a client config.

**Comment by filipeepifaniodeoliveira** [comment]
![image](https://user-images.githubusercontent.com/15159039/93088525-6638f400-f670-11ea-9c1d-1af013d18348.png)

Any solution for this google login error?

**Comment by fabriziogelsi** [comment]
> ![image](https://user-images.githubusercontent.com/15159039/93088525-6638f400-f670-11ea-9c1d-1af013d18348.png)
> 
> Any solution for this google login error?

See at @csbenjamin  commented on 29 Jul, I used that to wait... and Work fine.

**Comment by filipeepifaniodeoliveira** [comment]
thanks, it worked perfectly

**Comment by ihor-zinchenko** [comment]
same for me

**Comment by BruneXX** [comment]
Hi @jaibatrik Will there be a fix for this in a new release?, I have no problem to implement it if you guys put me up to date on what is needed here. Thanks!

**Comment by fabriziogelsi** [comment]
> Hi @jaibatrik Will there be a fix for this in a new release?, I have no problem to implement it if you guys put me up to date on what is needed here. Thanks!

I can give you a hand too, if you need...

**Comment by ihor-zinchenko** [comment]
i delete that plugin and do it by google/fb api, that is best solution

**Comment by fabriziogelsi** [comment]
> i delete that plugin and do it by google/fb api, that is best solution

Sometimes... The libraries don't help too much when you deep in the use... But Anyway I think is a good tool. In the other hand, can you share with us your solution? Do you have a repo? @ihor-zinchenko

**Comment by BruneXX** [comment]
@fabriziogelsi thanks! :) I'll take a look at this behavior and I'll propose a solution soon. And @ihor-zinchenko I don't think that will be better.. As a matter of fact, we (the community) are creating packages like this in order to help each other

**Comment by BruneXX** [comment]
> TypeScript is still not supporting `Promise.allSettled`.

@jaibatrik I think we can use promise.allSettled for angular 9/10 it should be supported, take a look at this: 
https://stackoverflow.com/questions/60276013/property-allsettled-does-not-exist-on-type-promiseconstructor-ts2339/60276174#60276174

**Comment by ihor-zinchenko** [comment]
> > i delete that plugin and do it by google/fb api, that is best solution
> 
> Sometimes... The libraries don't help too much when you deep in the use... But Anyway I think is a good tool. In the other hand, can you share with us your solution? Do you have a repo? @ihor-zinchenko

sure, tomorrow i give you an example how i do it, please remind me if i don't send it

**Comment by jaibatrik** [comment]
I see that many of you guys are facing this. Let me try to have a look and update you.

Thanks @BruneXX for the help. Do let me know your suggestions if you get some time.

**Comment by jaibatrik** [comment]
I am thinking of removing the `initState` from `SocialAuthService` altogether. Rather, the `initState` moves to individual providers. There, it will probably not be exposed, rather the initialization will happen on usage of `signIn` or something (as suggested by @csbenjamin) / on load lazily based on some config.

**Comment by jaibatrik** [comment]
I'll wait for a few days to see if any other suggestion comes up, otherwise will go ahead with the above changes. Expect the changes to be incorporated by next week :)

**Comment by BruneXX** [comment]
Hi @jaibatrik are you going to review this this week? I can help on anything you need, just let me know. I've already have a fork of this and started to make some changes, but if you are going through this soon I'll get rid of my changes. Thanks!

**Comment by jaibatrik** [comment]
> Hi @jaibatrik are you going to review this this week? I can help on anything you need, just let me know. I've already have a fork of this and started to make some changes, but if you are going through this soon I'll get rid of my changes. Thanks!

I started to make the changes last weekend, but could not finish. I am hoping to complete by this weekend. However, if you have changes ready, I wouldn't mind if you send a PR. We can review and discuss on it.

**Comment by jaibatrik** [comment]
Review the above.

**Comment by asifshapnil** [comment]
Hi, I get login providers not ready yet sometimes, and sometimes it works. Can you tell me why this is happening?

**Comment by zoltan-toth-mw** [comment]
This is an odd issue for us too with google login as just some of the users get this error.
This is how we use it:
```javascript
const googleLoginOptions = {
  scope: 'profile email openid'
};

@NgModule({
  declarations: [
   ...
  ],
  imports: [
    HttpClientModule,
    SocialLoginModule,
    CommonModule,
    RouterModule,
    ...
  ],
  exports: [
  ...
  ],
  providers: [
    {
      provide: APP_INITIALIZER,
      useFactory: (environmentService: EnvironmentService) => () => environmentService.init(),
      deps: [EnvironmentService],
      multi: true
    },
    {
      provide: 'SocialAuthServiceConfig',
      deps: [EnvironmentService],
      useFactory: (envService: EnvironmentService) => {
        return {
          autoLogin: false,
          providers: [
            {
              id: GoogleLoginProvider.PROVIDER_ID,
              provider: new GoogleLoginProvider(envService.configuration.googleClientId, googleLoginOptions),
            },
          ],
        } as SocialAuthServiceConfig;
      }
    },
   ....
  ]
})
```

**Comment by suhagsarak** [comment]
> > Are all of you trying to call `signIn` in `ngOnInit`? To think of it, that might cause problems.
> > Want to ask out of curiosity, what is the use case for calling `signIn` in the component load itself?
> 
> Do you also know how to verify the auth token on the backend? Which ENDPOINT should be used for this?

 Do you also know how to verify the auth token on the backend?  did you find

**Comment by ismailoffical80** [comment]
I also same issue witch reported above. is there an
![image](https://user-images.githubusercontent.com/56714862/95954287-7fba9080-0e14-11eb-8c7c-4e8f026fd9ed.png)
y solution or new release

**Comment by BruneXX** [comment]
@ismailoffical80 I think should be a new release soon @jaibatrik was working on that.

**Comment by jaibatrik** [comment]
Yeah, have been little busy lately... But this is being worked upon. We have arrived at an approach (see the commit I posted above). As soon as I get some time, I'll update the providers and create a release.

**Comment by rajatsaini736** [comment]
Hello everybody. if someone facing this error "Login providers not ready yet. Are there errors on your console?" after trying all these changes, maybe you should pause your browser's ad blocker and repeat the task (log in using google/ FB).

Hope it helps :)

**Comment by alexisqc92** [comment]
Did somebody was able to find a solution?

**Comment by alexisqc92** [comment]
So I was able to solve this by creating new Oauth credentials and assigning my IP. 

Also activate this: 

1)Activate both Analytics and Google Plus APIs on your project
2)Create new OAUTH 2.0 client credentials
     Add the Authorized Javascript Origins under Restrictions section
3)Use the new client id.

https://stackoverflow.com/questions/43964539/google-api-not-a-valid-origin-for-the-client-url-has-not-been-whitelisted-for/45761277#45761277

**Comment by jaibatrik** [comment]
Published a (sort of temporary) fix for this. Reopen if the issue is being seen in package version >=3.4.1.

**Comment by Selindek** [comment]
> Added an `initState` observable to `SocialAuthService`. It will complete once all the providers are ready. This should help with calling `signIn` on component load.
> 
> Usage: `this.authService.initState.subscribe(() => {}, console.error, () => {console.log('all providers are ready')});`

`initState` observable resolves half of the problem. But it seems it never calls the error() callback. So if one of the providers cannot be initialized then NONE of the callbacks are called, so I cannot handle the error properly.

**Comment by mohamedelmancy** [comment]
just you have to serve as https://localhost:4200/ not http://localhost:4200/
make the localhost as https not http

**Comment by jaibatrik** [comment]
> > Added an `initState` observable to `SocialAuthService`. It will complete once all the providers are ready. This should help with calling `signIn` on component load.
> > Usage: `this.authService.initState.subscribe(() => {}, console.error, () => {console.log('all providers are ready')});`
> 
> `initState` observable resolves half of the problem. But it seems it never calls the error() callback. So if one of the providers cannot be initialized then NONE of the callbacks are called, so I cannot handle the error properly.

Yeah, in its current state, the library works properly if all the providers are initialized (either success or failure). It cannot deal with a situation where any of the initializing promises does not resolve or reject. It depends on the individual providers to provide with an outcome after a reasonable time, rather than having a timeout within itself.

The problem with having the initialization distributed and not having any control on when they complete is that then we don't know when to trigger the `autoLogin` requests. And if that is not there, then the library can't know if a user is logged in or not.

**Comment by Bennie-higuru** [comment]
I have found something that works for me. I also tried calling the `signIn` function from the `ngOnInit` just to get the same error message. 

In my solution, I subscribe to the `initState`, and after it is initialized, I `signIn`.

```typescript
ngOnInit(): void {
  this.socialAuthService.initState.subscribe(value => {
    this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID).then(user => {
      console.log('GoogleContainerComponent.ngOnInit user:', user)
    });
  })
}
```

**Comment by despitegfx** [comment]
This worked for me. :)
So I thought of, if it works perfectly when a button is clicked, then I can use a timer in the *ngOnInit()* function.

As the application loads, the timer prevents ```this.authService.signIn(GoogleLoginProvider.PROVIDER_ID``` to load 
with the application concurrently. 

When the app finish loading and it's ready to execute any call, then the timer is ready and it executes the ```this.authService.signIn(GoogleLoginProvider.PROVIDER_ID)```. 

Now, the application will assumes it's a button clicked call.

const numbers = timer(1000);
    numbers.subscribe(call => this.authService.signIn(GoogleLoginProvider.PROVIDER_ID));

**Comment by asirihewage** [comment]
I had the same problem. Allowing cookies and popups fixed the issue.

**Comment by ewwwgiddings** [comment]
I'm getting this error while using version  ^3.2.2 and it breaks prerendering. I am not calling it in any ngOnInit or without user interaction. Anyone have experience with how to fix this in this case?

**Comment by veton** [comment]
In my case Vk was blocked, so its provider failed to initialize, and rest of the providers did not work either. This bug should be reopened.

**Comment by jaibatrik** [comment]
@veton which version are you using? We addressed this issue sometime back so that all providers are not blocked because of one failure. Could you please check?

**Comment by ewwwgiddings** [comment]
It was fixed but does the newest version breaks on Angular 10? I can't find the issue where we talked about it but I think this is the project where there was a fix but can't use it cause I'm on 10. I've been meaning to look into it if it is but my switch to Universal is taking forever.

**Comment by BruneXX** [comment]
Hi @ewwwgiddings I'm working with angular 11.2.1(latest stable Today) I haven't tried the v3.5.4 yet, I'm working with 3.2.2 yet, what kind of issue are you experiencing?

**Comment by sefatanam** [comment]
core.js:4610 ERROR Error: Uncaught (in promise): Login providers not ready yet. Are there errors on your console?
    at resolvePromise (zone-evergreen.js:798) [angular]
    at resolvePromise (zone-evergreen.js:750) [angular]
    at :4200/polyfills.js:10264:21 [angular]
    at Object.onInvokeTask (core.js:28183) [angular]
    at drainMicroTaskQueue (zone-evergreen.js:569) [<root>]
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:484) [<root>]
    at invokeTask (zone-evergreen.js:1621) [<root>]
    at HTMLButtonElement.globalZoneAwareCallback (zone-evergreen.js:1647) [<root>]
    
    
    Google authentication worked, but facebook doesnt work.

**Comment by kaessajidi** [comment]
After some investigation, I'm reproducing this issue on Ms Edge only. The reason is the tracking blocker who prevent google and fb js files to be loaded. 

initialize(config) {
  ...
            **.finally(() => {
            this.initialized = true;a
            this._initState.next(this.initialized);
            this._initState.complete();
        });**

The issue is related to the finally block which is not executed when the scripts have been blocked. if you force it to true by the debugger, the button works fine.
this.initialized.

**Comment by Damika-Anupama** [comment]
> I'm facing the same issue
![image](https://user-images.githubusercontent.com/63784444/167236465-325073bf-3a85-4c1c-a6be-5448b8f9c811.png)


**app.module.ts**

```
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';

import {AppRoutingModule} from './app-routing.module';
import {AppComponent} from './app.component';
import {HomeComponent} from './view/home/home.component';

// $.widget.bridge('uibutton', $.ui.button);
import 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js';
import 'admin-lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js';
import 'admin-lte/dist/js/adminlte.js';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
import {MatSliderModule} from '@angular/material/slider';
import {MatIconModule} from '@angular/material/icon';
import {MatBadgeModule} from '@angular/material/badge';
import {MatCardModule} from '@angular/material/card';
import {MatDialogModule} from '@angular/material/dialog';
import {SearchTabComponent} from './view/pop-ups/search-tab/search-tab.component';
import {WelcomeComponent} from './view/welcome/welcome.component';
import {SignInComponent} from './view/sign-in/sign-in.component';
import {SignUpComponent} from './view/sign-up/sign-up.component';
import {NotFoundComponent} from './view/not-found/not-found.component';
import {HomeRoutingModule} from './view/home/home-routing.module';
import {HomeModule} from './view/home/home.module';
import {FormsModule, ReactiveFormsModule} from '@angular/forms';
import {HttpClientModule} from '@angular/common/http';
import {MatSnackBarModule} from '@angular/material/snack-bar';
import {MAT_RADIO_DEFAULT_OPTIONS, MatRadioModule} from '@angular/material/radio';

import {GoogleLoginProvider, SocialAuthService, SocialAuthServiceConfig, SocialLoginModule} from 'angularx-social-login';
import {environment} from '../environments/environment';
import {httpInterceptorProvider} from '@src/app/service/interceptors/interceptor-barrel';
import { NgbCarouselModule, NgbModule } from '@ng-bootstrap/ng-bootstrap';
import {MatProgressBarModule} from "@angular/material/progress-bar";
import {MatMenuModule} from "@angular/material/menu";
import { ForgotPasswordComponent } from './view/forgot-password/forgot-password.component';
import { ServerErrorComponent } from './view/server-error/server-error.component';

@NgModule({
  declarations: [
    AppComponent,
    ...
  ],
  imports: [
   ...
    SocialLoginModule,
    
  ],
  providers: [
    {
      provide: 'SocialAuthServiceConfig',
      useValue: {
        autoLogin: false,
        providers: [
          {
            id: GoogleLoginProvider.PROVIDER_ID,
            provider: new GoogleLoginProvider(
              environment.googleClientId
            )
          }
        ],
        onError: (err) => {
          console.error(err);
        }
      } as SocialAuthServiceConfig,
    }],
  bootstrap: [AppComponent]
})
export class AppModule {
}
```
app.component.html

```
<a class="btn btn-block btn-danger g-signin2" (click)="loginWithGoogle()">
            <i class="fab fa-google-plus mr-2 "></i> Sign in using Google
          </a>
```

app.component.ts

```
ngOnInit(): void {
  }

googleLoginOptions = {
    scope: 'profile email'
  }; // https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauth2clientconfig
  
  loginWithGoogle(): void {
    this.socialAuthService.signIn(GoogleLoginProvider.PROVIDER_ID, this.googleLoginOptions).then(data =>{
      console.log(data)
    });
  }
```
Can you please watch my case
